import Head from 'next/head'
import ChevronRightIcon from '@mui/icons-material/ChevronRight';
import styles from '@/styles/Forum.module.css'
import Navbar from '@/components/Navbar'
import DiscussionAnalytics from '@/components/Forum/DiscussionAnalytics'
import DiscussionSummary from '@/components/Forum/DiscussionSummary'

export default function Forum() {
  return (
    <>
      <Head>
        <title>Diskuskuy</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link href="https://fonts.googleapis.com/css2?family=Raleway:wght@400;700&display=swap" rel="stylesheet"></link>
      </Head>
      <Navbar />
      <main className={styles.main}>
        <div className='flex flex-row items-center text-xs pb-10'>
          <a className='cursor-pointer'>Sistem Interaksi - Gasal 2020/2021</a>
          <ChevronRightIcon />
          <a className='cursor-pointer'>Forum Diskusi Minggu ke-1</a>
          <ChevronRightIcon />
          <a className='cursor-pointer'>Thread: Mari kita berkenalan dan bercerita..... 😉</a>
        </div>
        <div className='flex flex-row gap-5'>
          <div className='flex flex-col basis-3/4 gap-5'>
            <div className="block p-6 bg-white border rounded-lg flex flex-col gap-2">
              <p>test</p>
            </div>
          </div>
          <div className="flex flex-col basis-1/4 gap-5">
            <DiscussionAnalytics />
            <DiscussionSummary />
          </div>
        </div>
      </main>
    </>
  )
}
