import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
      <div className="container pt-10">
        <div
          className="block p-6 bg-white border border-gray-200 rounded-lg shadow dark:bg-gray-800 dark:border-gray-700 dark:hover:bg-gray-700"
        >
          <h5 className="mb-2 text-2xl font-bold tracking-tight text-gray-900 dark:text-white">
            Sistem Interaksi
          </h5>
          <p className="font-normal text-gray-700 dark:text-gray-400">
            (Gasal 2020/2021)
          </p>
        </div>
        <div
          className="block p-6 bg-white border border-gray-200 rounded-lg shadow dark:bg-gray-800 dark:border-gray-700 dark:hover:bg-gray-700"
        >
          <h5 className="mb-2 text-2xl font-bold tracking-tight text-gray-900 dark:text-white">
            Sistem Interaksi
          </h5>
          <p className="font-normal text-gray-700 dark:text-gray-400">
            (Gasal 2020/2021)
          </p>
        </div>
        <div
          className="block p-6 bg-white border border-gray-200 rounded-lg shadow dark:bg-gray-800 dark:border-gray-700 dark:hover:bg-gray-700"
        >
          <h6 className="mb-2 text-2xl font-bold tracking-tight text-gray-900 dark:text-white">
            Week 1
          </h6>
          <p className="font-normal text-gray-700 dark:text-gray-400">
            Forum Diskusi
          </p>
        </div>
      </div>
      </main>
    </>
  )
}
