import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import DosenInfo from '@/components/Home/DosenInfo'
import Navbar from '@/components/Navbar'
import DiscussionAnalytics from '@/components/Forum/DiscussionAnalytics'
import Profile from '@/components/Profile'

const dosenInfoDummy = [
  {
    'name': 'Fulan bin Fulan',
    'teachingClass': 'X',
    'photoUrl': '/teacher-img.png'
  },
  {
    'name': 'Nobunaga Tonarigumi',
    'teachingClass': 'Y',
    'photoUrl': '/teacher-img.png'
  },
  {
    'name': 'Mahmud bin Isnin',
    'teachingClass': 'Z',
    'photoUrl': '/teacher-img.png'
  },
];

const courseName = 'Sistem Interaksi';

const term = 'Gasal 2020/2021';

const courseDescription = 'Pada mata kuliah ini, teman-teman akan belajar mengenai prinsip-prinsip desain interaksi dan penerapannya pada pengembangan produk digital.'

export default function Home() {
  return (
    <>
      <Head>
        <title>Diskuskuy</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin />
        <link href="https://fonts.googleapis.com/css2?family=Raleway:wght@400;700&display=swap" rel="stylesheet"></link>
      </Head>
      <Navbar />
      <main className={styles.main}>
        <div className="flex flex-col gap-5">
          <div
            className="block p-6 h-44 bg-cover bg-[url('/header.png')] bg-[#646E9E] border rounded-lg text-white"
          >
            <h5 className="mb-2 text-2xl font-bold tracking-tight">
              {courseName}
            </h5>
            <p className="font-normal">
              ({term})
            </p>
          </div>
          <div
            className="block p-6 bg-white border rounded-lg shadow"
          >
            <div className='flex flex-row gap-2'>
              <div className='basis-1/2 flex flex-col gap-5'>
                <h5 className="mb-2 text-2xl font-bold tracking-tight text-gray-900">
                  Selamat Datang
                </h5>
                <p>
                  di mata kuliah {courseName} Semester {term}
                </p>
                <p>
                  {courseDescription}
                </p>
                <div className='flex flex-row items-center gap-2'>
                  <img src='/pdf-icon.png' width={'30px'}/>
                  <div className='flex flex-col'>
                    <p className='font-bold'>Buku Rancangan Pengajaran Sistem Interaksi</p>
                    <p>(Revisi 1 September 2020)</p>
                  </div>
                </div>
              </div>
              <div className='basis-1/2'>
                <h5 className="mb-2 text-2xl font-bold tracking-tight text-gray-900">
                  Tim Pengajar
                </h5>
                <div className='flex flex-row flex-wrap gap-2'>
                  {dosenInfoDummy.map((object, i) => 
                    <DosenInfo
                      key={i}
                      photoUrl={object.photoUrl}
                      name={object.name}
                      teachingClass={object.teachingClass}
                    />
                  )}
                </div>
              </div>
            </div>
          </div>
        </div>
      </main>
    </>
  )
}
