import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
      <div className="container">
        <div
          className="block p-6 my-3 bg-white border border-gray-200 rounded-lg shadow dark:bg-gray-800 dark:border-gray-700 dark:hover:bg-gray-700"
        >
          <h5 className="mb-2 text-2xl font-bold tracking-tight text-gray-900 dark:text-white">
            Sistem Interaksi
          </h5>
          <p className="font-normal text-gray-700 dark:text-gray-400">
            (Gasal 2020/2021)
          </p>
        </div>
        <div
          className="block p-6 my-3 bg-white border border-gray-200 rounded-lg shadow dark:bg-gray-800 dark:border-gray-700 dark:hover:bg-gray-700"
        >
          <h5 className="mb-2 text-2xl font-bold tracking-tight text-gray-900 dark:text-white">
            Sistem Interaksi
          </h5>
          <p className="font-normal text-gray-700 dark:text-gray-400">
            (Gasal 2020/2021)
          </p>
        </div>
        <div
          className="block p-6 my-3 bg-white border border-gray-200 rounded-lg shadow dark:bg-gray-800 dark:border-gray-700 dark:hover:bg-gray-700"
        >
          <h6 className="mb-2 text-2xl font-bold tracking-tight text-gray-900 dark:text-white">
            Week 1
          </h6>
          <div>
            <p className="font-normal text-gray-700 dark:text-gray-400">
              Forum Diskusi Minggu ke-1
            </p>
            <div className='grid grid-cols-2 mt-2'>
              <div className={styles.card}>
                <div className='grid grid-cols-6'>
                  <div className='col-start-1 col-end-6 group flex items-center'>
                    <img className="shrink-0 h-12 w-12 rounded-full" src="..." alt="" />
                    <div className='rtl:mr-3 ml-3'>
                      <p className="font-normal text-green-700 dark:text-green-400">
                        Thread
                      </p>
                      <h6 className='tracking-tight text-gray-900 dark:text-white'>
                        Mari kita berkenalan dan bercerita... ;)
                      </h6>
                      <p className='' style={{"font-size":"10px", "width":"100%", "margin":"0", "padding":"0"}}>
                        Fulan bin Fulan | 7 Maret 2023 (17.00 WIB)
                      </p>
                    </div>
                  </div>
                  <div className='col-end-7 col-span-1 p-2'>
                    <button class="bg-transparent hover:bg-green-500 text-green-700 font-semibold hover:text-white py-2 px-4 border border-green-500 hover:border-transparent rounded">
                      Lihat
                    </button>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      </main>
    </>
  )
}
