import Head from "next/head";
import styles from "@/styles/Home.module.css";
import Navbar from "@/components/Navbar";
import { login } from "@/api/auth";
import { useRouter } from "next/router";
import { useState, useEffect } from "react";
import { setCookies, getCookies } from "cookies-next";

export default function Login() {
  const router = useRouter();

  const [isLoading, setIsLoading] = useState(false)
  const [username, setUsername] = useState("");
  const [password, setPassword] = useState("");

  const handleChangeUsername = (event) => {
    setUsername(event.target.value);
  };

  const handleChangePassword = (event) => {
    setPassword(event.target.value);
  };

  const handleLogin = (event) => {
    event.preventDefault();
    setIsLoading(true)
    const requestBody = JSON.stringify({
      username: username,
      password: password,
    });
    login(requestBody).then((data) => {
      setCookies("auth", JSON.stringify(data));
      if (data) router.replace(`/`);
    }).finally(() => {
      setIsLoading(false)
    })
  };

  return (
    <>
      <Head>
        <title>Login</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin />
        <link
          href="https://fonts.googleapis.com/css2?family=Raleway:wght@400;700&display=swap"
          rel="stylesheet"
        ></link>
      </Head>
      <Navbar />
      <main className={styles.main}>
        <div className="relative flex flex-col justify-center overflow-hidden">
          <div className="w-full p-6 m-auto bg-white rounded-md shadow-xl shadow-green-600/40 ring ring-2 ring-green-600 lg:max-w-xl">
            <h1 className="text-3xl font-semibold text-center text-green-700 underline uppercase ">
              Login
            </h1>
            <form onSubmit={handleLogin} className="mt-6">
              <div className="mb-2">
                <label
                  for="username"
                  className="block text-sm font-semibold text-gray-800"
                >
                  Username
                </label>
                <input
                  value={username}
                  onChange={handleChangeUsername}
                  required
                  type="text"
                  className="block w-full px-4 py-2 mt-2 text-green-700 bg-white border rounded-md focus:border-green-400 focus:ring-green-300 focus:outline-none focus:ring focus:ring-opacity-40"
                />
              </div>
              <div className="mb-2">
                <label
                  for="password"
                  className="block text-sm font-semibold text-gray-800"
                >
                  Password
                </label>
                <input
                  value={password}
                  onChange={handleChangePassword}
                  required
                  type="password"
                  className="block w-full px-4 py-2 mt-2 text-green-700 bg-white border rounded-md focus:border-green-400 focus:ring-green-300 focus:outline-none focus:ring focus:ring-opacity-40"
                />
              </div>
              <a href="#" className="text-xs text-green-600 hover:underline">
                Forget Password?
              </a>
              <div className="mt-6">
                {/* <button className="w-full px-4 py-2 tracking-wide text-white transition-colors duration-200 transform bg-green-700 rounded-md hover:bg-green-600 focus:outline-none focus:bg-green-600">
                            Login
                        </button> */}
                <input
                  type={"submit"}
                  value={isLoading ? "Loading..." :"Login"}
                  className="w-full px-4 py-2 tracking-wide text-white transition-colors duration-200 transform bg-green rounded-md hover:bg-green-600 focus:outline-none focus:bg-green-600"
                />
              </div>
            </form>

            <p className="mt-8 text-xs font-light text-center text-gray-700">
              {" "}
              Don't have an account?{" "}
              <a href="#" className="font-medium text-green hover:underline">
                Sign up
              </a>
            </p>
          </div>
        </div>
      </main>
    </>
  );
}

export async function getServerSideProps({ req, res }) {
  if (getCookies({ req, res })?.auth) {
    return {
      redirect: {
        permanent: false,
        destination: "/",
      },
    };
  }
  
  return {
    props: {}
  }
}
